export { default as id1 } from "./bulldog-ingles.jpg";
export { default as id2 } from "./caniche.jpg";
export { default as id3 } from "./chihuahua.jpg";
export { default as id4 } from "./Chow_Chow.jpg";
export { default as id5 } from "./doberman.jpg";
export { default as id6 } from "./husky-m.jpg";
export { default as id7 } from "./Labrador retriever.jpg";
export { default as id8 } from "./Pastor aleman.jpg";
export { default as id9 } from "./pomerania.jpg";
export { default as id10 } from "./Rottweiler.jpg";
export { default as id11 } from "./shih_tzu.jpg";
export { default as id12 } from "./Short-haired-Dachshund.jpg";
export { default as id13 } from "./Egyptian Mau.jpg";
export { default as id14 } from "./gato balinés.jpg";
export { default as id15 } from "./gato ragdoll.jpg";
export { default as id16 } from "./gato_esfinge.jpg";
export { default as id17 } from "./gato-bosque-de-Noruega.jpg";
export { default as id18 } from "./gato-devon-rex.jpg";
export { default as id19 } from "./gato-exotico.jpg";
export { default as id20 } from "./gato-habana.jpg";
export { default as id21 } from "./gato-himalayo.jpg";
export { default as id22 } from "./gato-manx.jpg";
export { default as id23 } from "./gato-somalí.jpg";
export { default as id24 } from "./oriental pelo corto.jpg";
